#+TITLE:      A Thought About Uber
#+AUTHOR:	Yaniv
#+EMAIL:	yanivdll@gmail.com
#+DATE:     2015-12-06
#+URI:        
#+STATUS:   draft
#+KEYWORDS:   
#+TAGS:       uber
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

Yesterday, while walking my dog at night, I noticed a black car parking in the street, engine still on. Two guys in the front seats, sitting in an inward angle and leaning toward each other, while gazing their phones. 

Chill down, now, nothing dramatic is about to happen. Just one of those instances when my brain takes notice of a certain situation, and starts wandering in thoughts. I'm capturing this instance, which I thought was interesting. Unlike most of the thoughts that go through that same brain...

Anyway, it looked like they were two buddies that have just parked their car, and about to go out for a night out in a bar or a restaurt in the area. But then I noticed an Uber badge on the frot shield. Closer look, and they were finilizing an Uber ride.

And that's what straked me as an interesting situation. That interaction between a service provider (the driver) and a cutromer (the passanger), looked a lot like an interaction between two best friends. 

How does in possible? usually there is a striking distinction between the two[fn:1]. Think about the relations between a taxi or bus driers and their passangers - nothing to resemble friendliness. But with Uber, the driver can just as well be the passanger's best friend. Nothing to distinguish between them. The drive might have taken this ride so he can collect couple of benjimins that he will later spend with his friends, at the same bar as the passanger he've just droped. 

And when the driver and passanger can relate, there's no need for "service" or "customer care" anymore. Manares and being a good guy are the prevailing standards, and you don't drivers and passengers feel so comfortable, and so delighted with the service.

Just a thought.

* Footnotes

[fn:1] [[https://youtu.be/xWVxI6XZAuE][This scene]] from [[http://www.imdb.com/title/tt0137523/][Fight Club]] comes to mind.
 
