#+TITLE:       Blog Writing - Our First Meeting
#+AUTHOR:	Yaniv
#+EMAIL:	yanivdll@gmail.com
#+DATE:     2016-01-10
#+URI:        
#+STATUS:   
#+KEYWORDS:   
#+CATEGORY:  writing
#+TAGS:       meetup
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

Our Blog Writing meetup has taken off to a great start! Last Wednesday 18 of us met for the first time to discuss the vision of our group, share personal goals and talk about writing and blogging. 

In case you've missed it, want to learn about our group, or just reminisce, here's the presentation we went through, followed by a turn-by-turn summary of the meeting[fn:1]. 

#+BEGIN_EXPORT html
#+BEGIN_HTML

<iframe src="https://docs.google.com/presentation/d/19fXAyS8pZob0vJL6byLrFEUoZSizO3LncBuWJp1-oTQ/embed?start=false&loop=false&delayms=3000" frameborder="0" width="600" height="366" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

#+END_HTML
#+END_EXPORT


** A Round of Introductions
I was taken aback by the level of experience and talent in the room - published authors, professional bloggers, writers and people for whom writing is a second nature. 
My selfish plan to surround myself with people, who, unlike me, know a thing or two about writing, and from whom I can nurture, succeeded beyond expectations!

Yet, I've learned that no matter how skillful writer you are, we probably share similar excused for not blogging as much as we would have liked to: we don't know what to write about, we're too afraid of what people will say[fn:2], we accumulate more drafts than our drawer can hold, and we keep promising ourselves that /this/ week /is/ the week. The week when we'll finally launch our blog.

Next, we talked about the definition of our group.

** Our mission
We would like to create a support group, which will encourage its members to maintain a blog, and post to it regularly and frequently[fn:3]. Our motto:

**Write. Post. Repeat.**

We also stated what's not part of our mission. Promoting, monetizing and making business out of our blogs are not what we'll focus on in this group.

Knowing the "what", it was time to talk about the "how".

** Meeting format
We'll meet once a month. Each meeting will have a theme. Examples for themes might be: setting up a blog, knowing our audience, writing style, voice, tone and authority. 

At the fist part of the meeting we'll talk about the theme. We might have someone from the group leading the discussion, external speaker or just an open discussion.

At the second part of the meeting, we will read posts, written by members of the group, and then share our feedback (more on that bellow...)

** Reading And Providing Feedback - Dry Run

Since it was the first meeting, we started off by reading couple of blog posts by other bloggers. Here are the links to these posts:
- [[http://www.joelonsoftware.com/news/fog0000000244.html][Example post 1 - No Title]]
- [[http://sethgodin.typepad.com/seths_blog/2002/01/index.html][Example post 2 - Boring]]

If you'll read them, you might share the same perception as people in the team had - these will probably not be nominated for the best blog posts of all times. They are short, lacking in style, superficial in their description and leave the reader hanging when it comes to the point they are trying to get across.

And yet, I started with them because of the influence they had on me. You see, when /I/ was procrastinating the launch of my site, working for more than a month on a [[http://prodissues.com/2015/05/ekko-for-ios.html][two paragraphs post]], putting deadlines just to see how they're being pushed from one week to the next, I needed inspiration. 

I decided to check the archives on Joel Spolsky's and Seth Godin's blogs. Those are two prolific bloggers, whom I follow, and I wanted to see how /their/ beginning looked like. I found that they sucked. Maybe even more than I do! 

I realized that unless I push that post live, even if it's crappy, I'll never be able to improve. Improvement, I understood, rely not only on the writing, but also on posting. Even more importantly, it will happen only if I do the writing and posting again and again. Hence the motto:

**Write. Post. Repeat**

** 5 Tips For Writing
We continued with a post by a member of the team - Sue Hollister Barr (known as Holly). I thought that will be the most interesting part of our meeting. I was right. Holly's post, "[[http://suehollisterbarr.com/my-personal-top-five-writing-tips/][Top Five Writing Tips]]"[fn:4], led to a passionate (at times heated) discussion on feedback. What type of feedback should we give? should it be pungent, critical and direct, or rather compassionate, positive and supportive, even if we think the post isn't that great?

Our guiding mission - support and encourage members to maintain a blog - made the answer clear. We should stick with the latter approach, and provide feedback that is as constructive as encouraging. 

Unfortunately, at the height of the discussion, one of the participants concluded that the group isn't the right fit for her, and decided to leave. That spoiled our excitement and enthusiasm, but served as reminder that keeping true to a vision might not be appealing to everyone.  

Overall, though, the evening was a big success. The RSVP list for our next meeting is probably the best evidence for that - it got fully booked couple of hours after announcing the date! 

I can't be more excited about the future of that team. 

* Other Group Resources
When not meeting, member of the group can still communicate, share posts, feedback, tips and learning with other members. Here's a link to our online hubs:

- [[https://www.facebook.com/groups/548895981933905][Facebook group]]
- [[http://www.meetup.com/Blog-writing/][Meetup page]]

* Footnotes

[fn:1] Here's what participants [[http://www.meetup.com/Blog-writing/events/227048354/][had to say]] about the meeting.

[fn:2] Hack - now that I know that some of the members in that team will read that post, I'm thinking twice than I would of, on every word I type...

[fn:3] To be more precise about it, we want each of the members to own a live blog, and to post to that blog at least once between our monthly meeting.

[fn:4] I use Holly's post as a reference while writing those lines...

