#+TITLE:      Fixing My Apple Extended Keyboard II
#+AUTHOR:	Yaniv
#+EMAIL:	yanivdll@gmail.com
#+DATE:     2016-01-15
#+URI:        
#+STATUS:   
#+KEYWORDS:   
#+CATEGORY: 
#+TAGS:     keyboards  
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

Couple of months ago I bought the Apple Extended Keyboard from EBay. I fell in-love with it immediately, and enjoyed typing in it more than I do with my Wasd Code[fn:1]. 

To my disappointment, though, few days after I got it, several keys started to show signs of weakness. The '8' key spouted multiple letters in every stroke. The 't' worked sporadically, and the '.' stopped responding altogether.

** First Aid
I looked up how to fix an AEK. Most of the articles I found helped me with dissembling the case and the board, pulling out key-caps and crack opening the alps switches. I learned to clean, scratch oxide and lubricate the switch internals to improve conductivity.  

These measures didn't work. I thought about buying a new AEK, but figured it will make no sense. This is a 30 years old model, and chances are each keyboard I'll buy will have similar chances of having broken keys. Yet, this is too good of a keyboard to abandon.

** Intensive Care
And so, I got myself deeper into the world of mechanical keyboards. I learned that I can desolder switches from the board and replace them with new ones, but I didn't find alps switches to buy. What I did find were Matias switches, which claim to be identical to the classic white Alps switches. 

I found a sample pack of Matias switches at [[https://mechanicalkeyboards.com/shop/index.php?l=product_detail&p=483][mechanicalkeyboards.com]]. It comes in a set of 5, and cost only 5.99$. I then ordered a [[http://www.amazon.com/gp/product/B00KR1CXTS?psc=1&redirect=true&ref_=oh_aui_search_detailpage][soldering kit]] from Amazon[fn:2]. My plan was to replace the malfunctioned keys. But when I got the Matias switches, I noticed that they are much clickier than the AEK's alps. I didn't want to have different typing experience, so I decided to replace the broken switches with functioning ones from keys I never use. I will then install the Matias switches for those rarely used keys.

Now that I had a plan, I went on to learn about soldering. I found through [[http://reddit.com/r/mechanical_keyboards/?][the /r/MechanicalKeyboards]] subreddit a series of YouTube videos about soldering[fn:3]. I think those videos were made around the time my AKE was manufactured, but they are as timeless as this keyboard. If you're into it, then take a look also at that video. I found it very helpful in figuring out how to melt the soldering in order to take off existing switches, and how to use the soldering pump for sucking away the solder from the circuit board.

Armed with the acquired knowledge, the whole process turned out to be easy, quick and actually, quit fun. In less than 10 minutes I had a renovated keyboard. And now, not only that I have the rolls-royce of keyboards back in shape, I also know how to take care of it the next time one of its parts shows signs of fatigue.

Here are some pictures that illustrate the process (I also included at the bottom of the article helpful links for further support):

#+CAPTION: The ingredients - the soldering kit
http://media.prodissues.com/images/2016/01/IMG_6290.jpg

#+CAPTION: The ingredients - the Matias clicky switches pack (2 out of the 5 that arrived in the pack)
http://media.prodissues.com/images/2016/01/IMG_6286.jpg

#+CAPTION: The before
http://media.prodissues.com/images/2016/01/IMG_6291.jpg

#+CAPTION: After opening the case
http://media.prodissues.com/images/2016/01/IMG_6287.jpg

#+CAPTION: Pulling out the circuit board

#+CAPTION: This is how the board looks from the back. That's where the soldering work will take place. Locate the soldering that connects the switches we want to remove. Notice the horizontal lines of solder pairs. Each line represent a row. Each pair connecting a switch. That should help you locate the switches to work on. 
http://media.prodissues.com/images/2016/01/IMG_6269.jpg 

#+CAPTION: When locating the solders, mark them. Otherwise it's easy to get confused and remove the wrong switch.
http://media.prodissues.com/images/2016/01/IMG_6270.jpg

#+CAPTION: Starting to work - remove the '8' key
http://media.prodissues.com/images/2016/01/IMG_6281.jpg

#+CAPTION: Melting the solder at around the '8' key switch
http://media.prodissues.com/images/2016/01/IMG_6273.jpg

#+CAPTION: That's how the rotten '8' switch looks like. Notice the oxide at the legs of the switch that causing this key to not work
http://media.prodissues.com/images/2016/01/IMG_6284.jpg

#+CAPTION: Now, move to pulling away the functional keys that I don't use. I plan to use the switches of the num-lock, '=' and '/'
http://media.prodissues.com/images/2016/01/IMG_6276.jpg

#+CAPTION: Look at the soldering of the num-lock - the legs are twisted. I don't want to apply physical force to straighten them. I'll take out the '-' switch instead
http://media.prodissues.com/images/2016/01/IMG_6272.jpg

#+CAPTION: Plugging in the new Matias switches (don't have picture of the actual soldering process)
http://media.prodissues.com/images/2016/01/IMG_6282.jpg

#+CAPTION: Putting the key-caps back (can you notice what's wrong in this picture?)
http://media.prodissues.com/images/2016/01/IMG_6283.jpg

#+CAPTION: Putting the board back into the case, and testing the keyboard with [[https://itunes.apple.com/us/app/typist/id415166115?mt=12][Typist]]
http://media.prodissues.com/images/2016/01/IMG_6289.jpg


** Other Useful Links
- [[https://ifixit.org/blog/4468/hack-it-better-apple-extended-keyboard-ii/][Hack It Better: Apple Extended Keyboard II]]
- [[https://www.ifixit.com/Teardown/Apple+Extended+Keyboard+II+Teardown/42138][Apple Extended Keyboard II Teardown]]
- [[http://lowendmac.com/2006/apples-extended-keyboard-ii-sequel-to-a-legend/][Apple’s Extended Keyboard II: Sequel to a Legend]]
- [[https://github.com/cfenollosa/aekii][Tuning an Apple Extended Keyboard II]]
- [[http://deskthority.net/wiki/Apple_Extended_Keyboard_II][Apple Extended Keyboard II (Deskthority)]]
- [[http://www.mactech.com/articles/mactech/Vol.05/05.01/Keyboardrepair/index.html][Keyboard Repair]]

* Footnotes

[fn:1]: That might change, though. I have high hopes from the [[https://www.massdrop.com/buy/granite-keycap-set][Granite Key-caps Set]] I've just committed to on Massdrop.

[fn:2] Can't be more satisfied with that kit.

[fn:3] [[https://www.youtube.com/watch?v=vIT4ra6Mo0s][Basic Soldering Lesson 1 - "Solder & Flux"]] - but I recommend that you'll also watch lessons 2 and 3.

