#+TITLE:      I Can Live Without A Mac
#+AUTHOR:	Yaniv
#+EMAIL:	yanivdll@gmail.com
#+DATE:     2015-12-20
#+URI:        
#+STATUS:   
#+KEYWORDS:   
#+TAGS:     mac, emacs  
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

Couple of months ago I listened to an episode of the [[http://technicaldifficulties.us/episodes/080-a-history-of-computing][technical difficulties]] podcast. In that episode Gabe Weatherhead ([[http://macdrifter.com/][macdrifter.com]]) and Erik Hess hosted [[https://twitter.com/drdrang][Dr. Drang]] and talked about the history of computing. 

At some point [fn:1], Gabe asked Dr. Drang what will he do if he can't use Mac anymore. I don't remember exactly what Dr. Drang's answer was, but for awhile, the question kept echoing in my head. The thought about Mac not being around at some point was terrifying. I can't go back to Windows. Never. And Linux never seen as an adventure I would have like taking. 

Since then, though, much have changed. 

At first, I was reintroduced to old fashion mechanical keyboards[fn:2]. I bought a couple of them; one for home and one for my office. Suddenly, typing using my laptop's keyboards [fn:3] feels awkward and unsatisfying, and I now do it as little as possible. 

Then, I took a step into the rabbit hole of Emacs, the timeless editor which is backed by a strong and lively community. It's built around the keyboard, so I stopped using the Apple's "magic" mouse as much as I used to. 

Lastly, since Emacs requires tinkering with Mac's internals, I got more comfortable and familiar with the terminal application, and with "UI-less" experiences.

Slowly, I've learned that my Mac is nothing but a strong processing device with a Retina display. With that realization, the idea of using a different platform, Windows is still not an option, stopped scaring me. To the contrary, that thought sparks curiosity in me... 

While switching away is still not an option, I feel as if I was cured from Apple's spell. I regained my ability to think critically on its products, and look more objectively on their alternatives. 

It's probably only me, though, [[http://prodissues.com/2015/11/leap-into-the-past-irc.html][cuddling with the past]]. Most users are probably welcoming the intersecting paths of Mac and iPad into a comp-let mongrel that will lock developers out of its internals. But now, at least, I'm less anxious about that trajectory. I /will/ be able to find my way elsewhere... 

[fn:1] [[http://soundcloud.com/techdiffpodcast/080-a-history-of-computing#t%25253D77:12][Here's]] a link to this section in the podcast.
[fn:2] Typing on mechanical keyboard makes me not wanting to stop writing... I learned about them in yet another podcast - [[https://www.relay.fm/cortex/1][Cortex]]
[fn:3] Except for the [[https://en.wikipedia.org/wiki/Apple_Extended_Keyboard][Apple Extended Keyboard]]. I actually bought one, and am loving it.
