#+TITLE:      About Beauty Pageant And UX
#+AUTHOR:	Yaniv
#+EMAIL:	yanivdll@gmail.com
#+DATE:     2015-12-26
#+URI:        
#+STATUS:   draft
#+KEYWORDS:   
#+TAGS:       ux
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

Last week Steve Harvey made one of the most emberasing mistakes possible, [[https://youtu.be/nmqAjr0xs04][announcing the wrong Miss Universe]]. It was such an awekward moment, that some have blamed the orginizers [[http://www.starpulse.com/news/index.php/2015/12/21/miss-universe-conspiracy-theory-many-s][with a conspiracy]] to generate publicity to the not so interesting contest. 

I blame the bad design of the ballot card Harvey was reading from for the screw up[fn:1]. Take a look at that card for a moment:
http://media.prodissues.com/images/2015/12/beauty_pegeant.jpg

It's clear that whomever designed this card tried to emphesise as much as possible the winner. "MISS UNIVERSE 2015" is printed in uppercase, triple the size of any other word in that card, and to the right of the other text. How is it possible, then, that with so much emphesis, Harvey got it so wrong? well, it /is/ the over emphesis that caused Harvey to over look the entire section.

Paradoxically, over emphesising the identity of Miss Universs caused the opposite. 

*** Dont Make Me Think
We humans, excell in patterns recognition. In fact, that's one of the main things that set us apart from machines. Identifying patterns allows us to digest and make sense of large amount of information [information architecture]. When inforamation is structured in a certain way, such as a list, sections, like the fron-page of a newspaper, paragraphs, or tables, we can absorbe large amount of it quickly, and with minimum effort. We generelize and make inferences from small amount of data, kind of like in statistics, where sampling a small subset allows us to make conclusions (with certain level of confidence) on larger population.

Once we identify a pattern in the information in front of us, we look for visual cues to identify hierarchies. Hirarchies are important, as they help us understand what information we should pay more attention too. Take the following list for example: 

#+BEGIN_HTML
<li>some text</li>
<li>some more text</li>
<li><strong>important text</strong></li>
<li>and yet some more text</li>
#+END_HTML


the most important item in that list might be the one on top, the bold one, or the one that's in larger fonts. Look at the list bellow for example, which is the element I want you to focus on:

That was easy, right? there's a patern - a vertical list of items. Within that pattern there's a hierarchy, manifested by the use of plain and bold text. Since most of the items are in plain text, the one that's bold stands out and call for our attention.

So, knowing that we think in patterns and in visual cues, how can a UX designer use it to achive goal?

To answer that, let's look at another, more complex example. This is a homepage of Times Magazin. Can you tell which is the top story of the day? the one that the editor think you /should/ read?

#+caption: Time magazin - can you tell what's the most important story?
http://media.prodissues.com/images/2015/12/times_homepage.png


*** Over-Emphesis

The thing is that we're so relyant on patterns and visual cues, that when we find them, we fixate on them and overlook anything else that don't fall into them. 

As a UX designer, one of the ways to screw up a pattern is by making, what I call, "over-emphesis". It happens when for example, the element we're trying to emphesis isn't only bigger or bolder, but also in a different position (sound familiar?), or when it's bigger /and/ in a different color. When using too many visual cues to highlight a certain information, chances are the user will overlook what we've tried to emphesis.

*** Back to the card
Let's go back to poor Harvey and his ballot card. Can you see the pattern? a vertical list on the left, written with similar style, and naming the 2 runner-ups. 
# You might already notice a pitfall in that design choice - our mental model tells us that a list is usually sorted in a descending order, putting the winner\1st runner at the top of the list. But since the order of announcemnt is reversed (3rd place first), this format might makes sense after all. 
The third piece of information is in the right, seems unrelated to the left list, hence draws less attention, asspecially when time is short and pressure is high.

So you can imaging Harvey looking at this card, tention increases quickly as the big moment approaches. He looks at the contenders. They're anxious, waiting to hear what's in the card conceled in his hand. Harvey has probably read more such cards in his life than books, but still at that moment, live at prime time, the pressure is different. These girls' future is in his hands. He looks at the card and his eyes go immediately to its top left (that's nature), and fixate on the list. Unconsciously he reads the first line. The information makes sense. Proceed. And so, he announce the 2nd runner. 

Next, the winner. The arena is almost erupted, and the excitement overtakes the crowd. Almost imposible to think consciously, and so his instincts takes over. What's more natural than reading the next item on the list?

*** Summary
So no, I don't think it's a conspiracy, but a bad UX. One that tried to make *sure* Harvey pay attention, tries too much though that it caused the oposite.


*** Update:
I just came across [[http://www.techinsider.io/design-experts-on-steve-harveys-miss-universe-flub-2015-12][this article]], which blames the card's design for Harvey's mistake, reinforcing the theory I've presented above.

** Reference
- [[http://bigthink.com/endless-innovation/humans-are-the-worlds-best-pattern-recognition-machines-but-for-how-long][Humans Are the World's Best Pattern-Recognition Machines, But for How Long?]]
- [[https://en.wikipedia.org/wiki/Apophenia][Human tendency to perceive meaningful patterns within random data]]

* Footnotes

[fn:1] At first I, too, couldn't help thinking that the mistake /was/ staged, especially when the camera kept focusing on miss Philippines before Harvey corrected himself, as if to capture her reaction at that exact moment. But then Harvey's reaction, his quick departure from the stage, and the abrupt wrap up of the show led me to rethink. 

