#+TITLE:      Updating Org-Mode
#+AUTHOR:	Yaniv
#+EMAIL:	yanivdll@gmail.com
#+DATE:     2016-01-06
#+URI:        
#+STATUS:   draft
#+KEYWORDS:   
#+CATEGORY: Emacs
#+TAGS:     emacs, org-mode  
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 

I want to use org-reveal, so I can creat a text based presentations. I like the way reveal presentations are looking like, and also found this package that allows me to create a reveal presentation out of an org file. What can be better...?

I went ahead and installed the reveal and the org-reveal packages. That didn't work out at first, and after doing mayham to my Emacs configuration [ADD LINK TO THE POST HERE], I figured that all I had to do is update my org package to version 8.3, instead of the 8.2.10 that comes pre-installed with my version of Emacs (v24.5.1). 

So here we go.

1. Clone the org repository to my ~lisp~ folder
#+BEGIN_SRC sh
 ~/.emacs.d $ git clone  git://orgmode.org/org-mode.git lisp/org-mode/
#+END_SRC

2. Reading the documentation... http://orgmode.org/org.html#Installation

3. Since I cloned from git, I had to install the package by:
#+BEGIN_SRC sh
 ~/.emacs.d $ cd lisp/org-mode
 ~/.emacs.d/lisp/org-mode $ make autoloads
#+END_SRC

4. Now, Emacs knows to load the new version of org, instead of the default one. All I had to add is a path to the org package that I've downloaded, like this:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/org-mode/lisp")
#+END_SRC

Loading Emacs again, and checking org version (~M-x org-version~), I get this message:

#+BEGIN_SRC emacs-lisp
Org-mode version 8.3.2 (release_8.3.2-465-gaab464 @ /Users/ygilad/.emacs.d/lisp/org-mode/lisp/)
#+END_SRC

which is good...




    
